# Generated by Django 5.1.2 on 2024-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('upperTemperature', models.IntegerField()),
                ('lowerTemperature', models.IntegerField()),
                ('upperHumidity', models.IntegerField()),
                ('lowerHumidity', models.IntegerField()),
                ('upperLight', models.TextField()),
                ('lowerLight', models.TextField()),
            ],
        ),
    ]
